### ISSUE TITLE
Please Help! Minecraft forge versions not opening with Grue

### ISSUE THREAD

**Issue by DMBurch06** [Shinoow/Grue#21]
I'm really new to all of this and I'm doing my best to try and mod Minecraft for my nephew. And I really need help. I believe I have downloaded the correct versions of everything but I keep getting the following error message while trying to open forge saying that I don't have the correct versions?

![Screenshot (2)](https://user-images.githubusercontent.com/59068838/71213213-cc225780-2267-11ea-9669-fe3430c93177.png)

Please, any help would be really appreciated.
Thanks in advance!

**Comment by Andromander** [comment]
You're trying to run a version of Forge that is outdated by numerous versions. Recommended Version of Forge is not always the best version to use at this point, always use the Latest Version.

**Comment by DMBurch06** [comment]
> You're trying to run a version of Forge that is outdated by numerous versions. Recommended Version of Forge is not always the best version to use at this point, always use the Latest Version.

Correct me if I'm wrong. So on this computer, there is Minecraft version 1.15.1. I read someplace that forge only works when paired with the exact same corresponding version of Minecraft?
Again, I'm no expert. Just trying to help my nephew out.

**Comment by Andromander** [comment]
Minecraft 1.15.1 is too high a version, too, as none of the mods are available on that version.

You'll need the Latest Version of Forge for Minecraft 1.12.2. When you are on the Forge website, you are given two options to download for 1.12.2: Latest and Recommended. While Recommended is there because it is considered "stable", it is several months old and misses some changes in Latest, so it's best to the Latest for that version.

**Comment by DMBurch06** [comment]
> Minecraft 1.15.1 is too high a version, too, as none of the mods are available on that version.
> 
> You'll need the Latest Version of Forge for Minecraft 1.12.2. When you are on the Forge website, you are given two options to download for 1.12.2: Latest and Recommended. While Recommended is there because it is considered "stable", it is several months old and misses some changes in Latest, so it's best to the Latest for that version.

Oh ok. Well, how do I go about downloading an earlier version of Minecraft? Is that even possible?

**Comment by Shinoow** [comment]
Based on your screenshot, you're already running Minecraft 1.12.2. You just need to update Forge to a newer version for that Minecraft version (you're currently using 14.23.5.2768, you need 14.23.5.2847).
Much like what Andromander has said, download the installer for the "latest" version of Forge for Minecraft 1.12.2, instead of the "recommended".
