### ISSUE TITLE
Remove the dependency for Forge version 2847 for 1.12.2

### ISSUE THREAD

**Issue by theStrobilus** [Shinoow/Grue#22]
I've been trying to get a modpack working with Aether tall grass (which renders weirdly if done in any Forge version past 2843) and I also am wanting to include this mod, but you have an unnecessary dependency for Forge 2847. And, Grue is not open source, meaning I had to decompile the mod myself to fix the SINGLE LINE OF CODE.

please fix!

**Comment by Andromander** [comment]
This sounds more like a problem with Aether not working properly rather than Grue enforcing a minimum functional version.

**Comment by theStrobilus** [comment]
It is technically an issue with Aether Legacy, but I can guarantee you that Grue would run perfectly fine on Forge 2843, as I really doubt it uses the newest features of 1.12.2 Forge. As a matter of fact, I bet it could run on Forge 2768.

**Comment by Tamaized** [comment]
Have you actually tried to clone the source, set the forge version, and attempt a compile? Assumptions are bad.

**Comment by theStrobilus** [comment]
I tried doing that and it didn't work. Not really sure what I did wrong, I ran the .jar through the Fernflower decompiler, then used BON 2 for mapping, and then moved the files from the final jar product into a mod src folder, and the mappings weren't correct.

**Comment by Shinoow** [comment]
> And, Grue is not open source, meaning I had to decompile the mod myself to fix the SINGLE LINE OF CODE.

I don't recall anyone asking you to do that, so I don't think there's really room to complain about something you decided to spend your time on. Snark aside, this is more of a problem on their end rather than mine.

The bug itself in Aether Legacy exists due to the change done in Forge at https://github.com/MinecraftForge/MinecraftForge/commit/c2630d2a79d291f0ff364c02f74f8dee3e8aa77a, which based on the code comment prevents biomes being generated client-side in singleplayer. The effect this has on the Aether is that apparently 98% of the dimension is set to the vanilla Plains biome (as shown over at their issue tracker, https://gitea.gildedgames.com/GildedGames/The-Aether/issues/47).
Seemingly some part of the biome generation for that dimension is doing something client-side that should entirely be done on the server. I would have to dig through the source code for a better explanation, but based on what changed in Forge and what happens in the biome generation, I can only assume something isn't entirely handled correctly.

I could release two mod updates where I downgrade the Forge version, but with 14.23.5.2847 being the final release of Forge for 1.12.2 (as 1.14.4 is now LTS), I don't see much of a point in why I (or any modder, for that point) shouldn't enforce the latest stable version of Forge (in this case, also the final version) just because one mod has a visual bug there. I can't account for what Gilded Games prioritize their time on, but hopefully they can resolve the issue at hand in the near future.
If you can give me a good reason, I'll downgrade the Forge version of Grue and DarknessLib, but I'd rather not downgrade because of an unresolved visual bug present in another mod.

**Comment by theStrobilus** [comment]
While I fully agree that it is an issue with Aether Legacy, I still believe you should remove the specific version of Forge dependency the Grue mod has, as it's completely unnecessary and as I stated before, the mod probably doesn't need that specific version of Forge to function properly. I wouldn't really release this as a standalone update, though. Maybe just remove the line whenever you make a new update to the mod, as it wouldn't really harm anything and people who are using slightly older versions of Forge can be happy. (For whatever reason they are using it.)
